import unittest
import json
from unittest.mock import patch, MagicMock
from datetime import date
from decimal import Decimal
from pathlib import Path

from hermes.supervisor.state import RiskStateSnapshot
from hermes.supervisor.config import LlmSupervisorConfig, RiskConfig
from hermes.supervisor.llm_supervisor import LlmSupervisor, LlmSupervisorAdvice
from hermes.supervisor.utils.agy_delegator import delegate_to_agy
from hermes.domain.models import TradingMode


class TestAgyDelegation(unittest.TestCase):

    @patch("subprocess.Popen")
    @patch("pathlib.Path.exists")
    def test_delegate_to_agy_success(self, mock_exists, mock_popen):
        """Verify that delegate_to_agy successfully parses the response file generated by agy."""
        mock_exists.side_effect = lambda: True  # Simulating that files exist when checked

        # Mock the subprocess.Popen behavior
        mock_proc = MagicMock()
        mock_proc.poll.return_value = 0
        mock_popen.return_value = mock_proc

        # Mock response payload
        mock_response_payload = {
            "status": "success",
            "result": {
                "sentiment_score": 0.8,
                "sentiment_summary": "Strong bullish breakout expected.",
                "recommended_regime": "bull_run",
                "recommended_bias": "bullish"
            }
        }

        with patch("pathlib.Path.read_text", return_value=json.dumps(mock_response_payload)):
            with patch("pathlib.Path.write_text") as mock_write:
                with patch("pathlib.Path.unlink") as mock_unlink:
                    res = delegate_to_agy(
                        task_type="market_sentiment_analysis",
                        task_description="Analyze sentiment",
                        context={"mode": "scalp"}
                    )

        self.assertEqual(res["status"], "success")
        self.assertEqual(res["result"]["sentiment_score"], 0.8)
        self.assertEqual(res["result"]["recommended_regime"], "bull_run")

    @patch("subprocess.Popen")
    def test_delegate_to_agy_failure(self, mock_popen):
        """Verify that delegate_to_agy handles cases where no response is written gracefully."""
        mock_proc = MagicMock()
        mock_proc.poll.return_value = 1
        mock_proc.communicate.return_value = ("stdout error", "stderr error")
        mock_popen.return_value = mock_proc

        with patch("pathlib.Path.write_text"):
            with patch("pathlib.Path.unlink"):
                res = delegate_to_agy(
                    task_type="market_sentiment_analysis",
                    task_description="Analyze sentiment",
                    context={"mode": "scalp"}
                )

        self.assertEqual(res["status"], "error")
        self.assertIn("No response file generated", res["error"])

    @patch("hermes.supervisor.llm_supervisor.load_events_for_date")
    @patch("hermes.supervisor.llm_supervisor.build_summary")
    @patch("hermes.supervisor.llm_supervisor.build_prompts")
    @patch("hermes.supervisor.utils.agy_delegator.delegate_to_agy")
    def test_llm_supervisor_integration(self, mock_delegate, mock_build_prompts, mock_build_summary, mock_load_events):
        """Verify that LlmSupervisor.run_check triggers delegation to agy and prepends sentiment context."""
        
        # Setup config & snapshot
        config = LlmSupervisorConfig(
            enabled=True,
            api_url="https://api.openai.com/v1",
            model="openai/gpt-oss-120b:free",
            api_key_env="GOOGLE_API_KEY",
            check_interval_minutes=5,
            min_order_decisions=1,
            max_events_in_summary=50,
            max_trades_in_table=20,
            timeout_seconds=30,
            dry_run=True,
            trust_policy={},
            circuit_breaker={}
        )
        risk_cfg = RiskConfig(
            currency="USDT",
            max_daily_loss_abs=Decimal("500.0"),
            max_daily_loss_pct=Decimal("0.05"),
            max_drawdown_abs=Decimal("1000.0"),
            max_drawdown_pct=Decimal("0.10"),
            max_notional_per_symbol=Decimal("50000.0"),
            max_leverage=Decimal("20.0")
        )
        
        snapshot = RiskStateSnapshot(
            trading_day=date.today(),
            equity_start=Decimal("10000.0"),
            equity_now=Decimal("9800.0"),
            realized_pnl_today=Decimal("-200.0"),
            max_equity_intraday=Decimal("10000.0"),
            min_equity_intraday=Decimal("9800.0"),
            halted=False,
            halt_reason=None,
            unrealized_pnl=Decimal("-150.0")  # High PnL change -> triggers sentiment analysis
        )
        
        # Mock delegate response
        mock_delegate.return_value = {
            "status": "success",
            "result": {
                "sentiment_score": -0.9,
                "sentiment_summary": "Extremely bearish news drop.",
                "recommended_regime": "bear_panic",
                "recommended_bias": "defensive"
            }
        }
        
        mock_load_events.return_value = []
        mock_build_summary.return_value = MagicMock()
        mock_build_prompts.return_value = ("system prompt", "user prompt")
        
        supervisor = LlmSupervisor(
            config=config,
            risk_config=risk_cfg,
            events_dir=Path("/tmp"),
            logger=MagicMock()
        )
        
        # Mock LLM calling and parsing
        supervisor.call_llm = MagicMock(return_value="mock advice payload")
        supervisor.parse_advice = MagicMock(return_value=LlmSupervisorAdvice(
            trading_mode=TradingMode.SPOT_GRID,
            risk_multiplier=0.5,
            reasoning="Bearish market sentiment",
            raw_response="raw payload"
        ))
        
        advice = supervisor.run_check(
            today=date.today(),
            snapshot=snapshot,
            mode="scalp",
            situation_text="Initial situation context"
        )
        
        # Verify agy delegation was triggered
        mock_delegate.assert_called_once()
        
        # Verify that sentiment details were prepended to situation_text passed to build_prompts
        passed_situation_text = mock_build_prompts.call_args[1].get("situation_text")
        self.assertIn("EXTERNAL MARKET SENTIMENT (via Antigravity agy)", passed_situation_text)
        self.assertIn("Sentiment Score: -0.9", passed_situation_text)
        self.assertIn("Extremely bearish news drop.", passed_situation_text)
        self.assertIn("Initial situation context", passed_situation_text)


if __name__ == "__main__":
    unittest.main()
