"""
Delegation utility to dispatch complex market intelligence and self-healing tasks to Antigravity (agy).
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import time
from pathlib import Path
from typing import Any, Dict

logger = logging.getLogger("hermes.agy_delegator")


def delegate_to_agy(
    task_type: str,
    task_description: str,
    context: Dict[str, Any],
    timeout_seconds: int = 300,
) -> Dict[str, Any]:
    """
    Delegates a complex task (e.g. market sentiment analysis, code patching, autotuning) to Antigravity.
    Writes a request JSON, triggers agy CLI asynchronously, and reads the response JSON.
    """
    runtime_dir = Path("runtime")
    runtime_dir.mkdir(parents=True, exist_ok=True)

    request_id = f"req_{task_type}_{int(time.time())}"
    request_file = runtime_dir / f"agy_request_{request_id}.json"
    response_file = runtime_dir / f"agy_response_{request_id}.json"

    # Write request payload
    request_payload = {
        "request_id": request_id,
        "timestamp_ns": time.time_ns(),
        "task": task_type,
        "description": task_description,
        "context": context,
    }

    try:
        request_file.write_text(json.dumps(request_payload, indent=2, ensure_ascii=False), encoding="utf-8")
        logger.info(f"[AGY-DELEGATE] Request {request_id} written to {request_file}")
    except Exception as e:
        logger.error(f"[AGY-DELEGATE] Failed to write request file: {e}")
        return {"status": "error", "error": f"Failed to write request: {e}"}

    # Construct the agy command line
    # Using --dangerously-skip-permissions to avoid interactive prompt halts
    cmd = [
        "/home/korben/.local/bin/agy",
        "--dangerously-skip-permissions",
        "--print",
        f"Perform task: {task_description}. Analyze the request context from the file {request_file.resolve()} "
        f"and write the final outcome as a raw JSON matching the response schema to the file {response_file.resolve()}. "
        "Return ONLY the raw JSON in the file. Do not perform any other actions unless requested.",
    ]

    logger.info(f"[AGY-DELEGATE] Executing: {' '.join(cmd)}")

    try:
        # Launch agy in the background
        start_time = time.time()
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd=str(Path(".").resolve()),
        )

        # Poll until the response file appears, or timeout is reached, or process exits
        while time.time() - start_time < timeout_seconds:
            if response_file.exists():
                logger.info(f"[AGY-DELEGATE] Response file detected after {time.time() - start_time:.2f}s")
                break
            if process.poll() is not None:
                # Process exited early without creating the file
                stdout, stderr = process.communicate()
                logger.error(f"[AGY-DELEGATE] agy process exited with code {process.returncode}.\nStdout: {stdout}\nStderr: {stderr}")
                break
            time.sleep(2)
        else:
            logger.warning(f"[AGY-DELEGATE] Timeout waiting for {response_file}")
            try:
                process.terminate()
                process.wait(timeout=5)
            except Exception:
                process.kill()

        # Parse output
        if response_file.exists():
            try:
                response_data = json.loads(response_file.read_text(encoding="utf-8"))
                logger.info(f"[AGY-DELEGATE] Successfully received response for {request_id}")
                return response_data
            except Exception as e:
                logger.error(f"[AGY-DELEGATE] Failed to parse response JSON: {e}")
                return {"status": "error", "error": f"Parse error: {e}"}
        else:
            return {"status": "error", "error": "No response file generated by agy"}

    except Exception as e:
        logger.error(f"[AGY-DELEGATE] Execution error: {e}")
        return {"status": "error", "error": f"Execution error: {e}"}
    finally:
        # Cleanup temp request/response files to prevent clutter
        if request_file.exists():
            try:
                request_file.unlink()
            except OSError:
                pass
        if response_file.exists():
            try:
                response_file.unlink()
            except OSError:
                pass
