#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LLM_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${LLM_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

if [[ -f "${LLM_DIR}/configs/engine_defaults.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${LLM_DIR}/configs/engine_defaults.env"
  set +a
fi

: "${OUT_DIR:?OUT_DIR is required}"
: "${ENGINE_DIR:?ENGINE_DIR is required}"
: "${MODEL_DIR:?MODEL_DIR is required}"

BENCH_ITERS="${BENCH_ITERS:-100}"
REPORT_DIR="${OUT_DIR}/reports"
mkdir -p "${REPORT_DIR}"

RESULTS_JSON="${REPORT_DIR}/bench_results.json"

if command -v trtllm-bench >/dev/null 2>&1; then
  echo "[bench] Using trtllm-bench..."
  trtllm-bench \
    --engine_dir "${ENGINE_DIR}" \
    --max_input_len "${MAX_INPUT_LEN}" \
    --max_output_len "${MAX_OUTPUT_LEN}" \
    --num_iters "${BENCH_ITERS}" \
    --json "${RESULTS_JSON}"
else
  echo "[bench] Using smoke_local.py benchmark runner..."
  python3 "${LLM_DIR}/scripts/smoke_local.py" \
    --engine-dir "${ENGINE_DIR}" \
    --model-dir "${MODEL_DIR}" \
    --max-input-len "${MAX_INPUT_LEN}" \
    --max-output-len "${MAX_OUTPUT_LEN}" \
    --iterations "${BENCH_ITERS}" \
    --bench-json "${RESULTS_JSON}"
fi

TEMPLATE="${LLM_DIR}/reports/baseline_template.md"
BASELINE_MD="${REPORT_DIR}/baseline.md"

export RESULTS_JSON
export TEMPLATE
export BASELINE_MD
export ENGINE_DIR
export MAX_BATCH_SIZE
export MAX_INPUT_LEN
export MAX_OUTPUT_LEN

python3 - <<'PY'
import json
import os
import subprocess
from datetime import datetime, timezone

results_path = os.environ.get("RESULTS_JSON")
if not results_path or not os.path.exists(results_path):
    raise SystemExit("bench_results.json not found")

with open(results_path, "r", encoding="utf-8") as handle:
    data = json.load(handle)

p50 = data.get("p50", {})
p95 = data.get("p95", {})
peak_vram = data.get("peak_vram_mb", 0)

try:
    smi = subprocess.check_output(
        ["nvidia-smi", "--query-gpu=name,driver_version", "--format=csv,noheader"],
        text=True,
    ).strip()
    gpu_name, driver_version = (smi.split(",", 1) + ["unknown"])[:2]
    gpu_name = gpu_name.strip()
    driver_version = driver_version.strip()
except Exception:
    gpu_name = "unknown"
    driver_version = "unknown"

trtllm_version = "unknown"
tensorrt_version = "unknown"
try:
    import tensorrt_llm
    trtllm_version = tensorrt_llm.__version__
except Exception:
    pass
try:
    import tensorrt
    tensorrt_version = tensorrt.__version__
except Exception:
    pass

engine_manifest = os.path.join(os.environ.get("ENGINE_DIR", ""), "engine_manifest.json")
kv_cache_mode = "unknown"
if os.path.exists(engine_manifest):
    with open(engine_manifest, "r", encoding="utf-8") as handle:
        manifest = json.load(handle)
        kv_cache_mode = manifest.get("kv_cache_mode", "unknown")

replacements = {
    "{{DATE_UTC}}": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "{{GPU_NAME}}": gpu_name,
    "{{DRIVER_VERSION}}": driver_version,
    "{{TRTLLM_VERSION}}": trtllm_version,
    "{{TENSORRT_VERSION}}": tensorrt_version,
    "{{MAX_BATCH}}": os.environ.get("MAX_BATCH_SIZE", "1"),
    "{{MAX_INPUT_LEN}}": os.environ.get("MAX_INPUT_LEN", "2048"),
    "{{MAX_OUTPUT_LEN}}": os.environ.get("MAX_OUTPUT_LEN", "512"),
    "{{KV_CACHE_MODE}}": kv_cache_mode,
    "{{TTFT_P50_MS}}": f"{p50.get('ttft_ms', 0):.2f}",
    "{{TTFT_P95_MS}}": f"{p95.get('ttft_ms', 0):.2f}",
    "{{LAT_P50_MS}}": f"{p50.get('latency_ms', 0):.2f}",
    "{{LAT_P95_MS}}": f"{p95.get('latency_ms', 0):.2f}",
    "{{TOKS_P50}}": f"{p50.get('tokens_per_s', 0):.2f}",
    "{{TOKS_P95}}": f"{p95.get('tokens_per_s', 0):.2f}",
    "{{PEAK_VRAM_MB}}": f"{peak_vram:.2f}",
    "{{NOTES}}": "Generated by bench.sh",
}

with open(os.environ.get("TEMPLATE"), "r", encoding="utf-8") as handle:
    template = handle.read()

for key, value in replacements.items():
    template = template.replace(key, value)

with open(os.environ.get("BASELINE_MD"), "w", encoding="utf-8") as handle:
    handle.write(template)
PY

echo "[bench] Wrote ${RESULTS_JSON} and ${BASELINE_MD}"
